import React,{useEffect,useRef,useState} from 'react';
import {severityProfiles,validateAssessment} from './severity.mjs';
export default function AccidentPhoto({onChange}){
 const [image,setImage]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[assessment,setAssessment]=useState(null),[preparing,setPreparing]=useState(false);
 const generation=useRef(0),controller=useRef(null),input=useRef(null);
 useEffect(()=>()=>{generation.current++;controller.current?.abort();},[]);
 function clear(resetInput=true){generation.current++;controller.current?.abort();if(resetInput&&input.current)input.current.value='';setImage(null);setAssessment(null);setError('');setBusy(false);setPreparing(false);onChange(null);}
 async function upload(e){const file=e.target.files?.[0];clear(false);if(!file)return;const token=generation.current;
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setError('Choose JPEG, PNG or WebP, up to 8 MB.');e.target.value='';return;}
  setPreparing(true);try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/jpeg',.8);if(data.length>2800000)throw Error();if(token===generation.current){setImage(data);setPreparing(false);await analyze(data);}}catch{if(token===generation.current)setError('This image could not be opened. Try another photo.');}finally{if(token===generation.current)setPreparing(false);}
 }
 async function analyze(data=image){const token=++generation.current;setBusy(true);setError('');setAssessment(null);onChange(null);controller.current=new AbortController();const active=controller.current;const timer=setTimeout(()=>active.abort(),30000);
  try{const response=await fetch('/api/assess-accident',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:data}),signal:controller.current.signal});if(!response.headers.get('content-type')?.includes('application/json'))throw Error('Image assessment is not connected on this website yet. No severity has been assigned; routing remains unchanged.');const result=await response.json();if(!response.ok)throw Error(result.error||'Image assessment unavailable.');const checked=validateAssessment(result);if(token!==generation.current)return;setAssessment(checked);if(!checked.requiresReview)onChange({...checked,image:data});}
  catch(e){if(token===generation.current)setError(e.name==='AbortError'?'Assessment timed out. Retry or upload another photo. No severity has been assigned.':e.message);}finally{clearTimeout(timer);if(token===generation.current)setBusy(false);}
 }
 return <div className="photo-assessment"><label>Accident photo<small>Uploading sends the photo for automatic assessment. Avoid including identifying details.</small><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} aria-label="Accident photo"/></label>{preparing&&<p role="status">Preparing photo…</p>}{image&&<><img src={image} alt="Accident photo preview"/><div className="photo-actions"><button type="button" className="outline" onClick={()=>analyze()} disabled={busy}>{busy?'Assessing photo…':'Reassess photo'}</button><button type="button" className="text-button" onClick={clear}>Remove photo</button></div><small>Severity is determined by the image model; citizens cannot override it.</small></>}{error&&<p role="alert" className="error">{error}</p>}{assessment&&<div className="assessment-result"><b>{assessment.requiresReview?'Unable to determine severity — upload a clearer photo':`${severityProfiles[assessment.severity].label} traffic disruption`}</b><small>Image assessment · {assessment.confidence} confidence</small><p>{assessment.summary}</p><ul>{assessment.evidence.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}<small>Traffic impact only. Closure estimates are planning assumptions, not confirmed clearance times.</small></div>;
}
