import React,{useEffect,useMemo,useRef,useState} from 'react';
import TrafficMap from './TrafficMap.jsx';
import AccidentPhoto from './AccidentPhoto.jsx';
import {severityProfiles} from './severity.mjs';
import {buildRoadGraph,reroute,routeAffected} from './incidents.mjs';
import {pathMetrics,positionAlong} from './road-routing.mjs';
export default function IncidentExperience({baseRoute,network,roads,layer,focus,onPlan,onEmergency}){
 const [locked,setLocked]=useState(false),[assessment,setAssessment]=useState(null),[photoReset,setPhotoReset]=useState(0);
 const [plan,setPlan]=useState(null),[reports,setReports]=useState([]),[impact,setImpact]=useState(null),[location,setLocation]=useState(''),[details,setDetails]=useState(''),[command,setCommand]=useState(null),[armed,setArmed]=useState(false);
 const journey=useRef({progress:0,moving:false}),armedRef=useRef(false),route=plan||baseRoute;
 const graph=useMemo(()=>roads?buildRoadGraph(roads,network):null,[roads,network]);
 const locations=useMemo(()=>{const names=new Set();return (route?.edges||[]).filter(e=>{if(!e.name||names.has(e.name)||e.distance<40)return false;names.add(e.name);return true;}).map(e=>({name:e.name,position:e.points[Math.floor(e.points.length/2)]}));},[route]);
 useEffect(()=>{setAssessment(null);setPhotoReset(n=>n+1);setLocked(false);setPlan(null);onPlan(null);setReports([]);setImpact(null);setArmed(false);armedRef.current=false;setCommand(null);journey.current={progress:0,moving:false};},[baseRoute?.id]);
 function submitReport(place,demo=false){
  if(!route||!place||(!demo&&!assessment))return;const {progress,moving}=journey.current,report={id:Date.now().toString(),position:place.position,road:place.name,details:details.trim(),time:new Date().toLocaleTimeString(),demo,severity:demo?'high':assessment.severity,assessment:demo?{source:'Scenario',summary:'Major road obstruction'}:assessment};
  const next=[...reports,report],affected=routeAffected(route,progress,report),before=Math.max(0,Math.ceil(route.minutes*(1-progress)));
  const detour=affected?reroute(graph,route,progress,next):null;
  setReports(next);setImpact({report,affected,before,after:detour?.minutes,arrival:detour?new Date(Date.now()+detour.minutes*60000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):null,outcome:!affected?'Route unaffected':detour?'Plan updated':'No safe cached detour',oldPoints:route.points});
  if(detour){setLocked(false);setPlan(detour);onPlan(detour);journey.current={progress:0,moving};setCommand({id:Date.now(),action:moving?'start':'pause'});}
  else if(affected){setLocked(true);setCommand({id:Date.now(),action:'pause'});}
  setDetails('');setAssessment(null);setPhotoReset(n=>n+1);
 }
 function updateJourney(s){journey.current=s;if(armedRef.current&&s.progress>=.18&&s.progress<.9){armedRef.current=false;setArmed(false);
   // Pick a demonstrable closure ahead with a viable road detour; never invent one.
   const m=pathMetrics(route.points);let candidate;
   for(const fraction of [.65,.5,.8,.4]){const position=positionAlong(m,fraction),r={id:'probe',position,severity:'high'};if(reroute(graph,route,s.progress,[...reports,r])){candidate={name:'Accident ahead on ambulance route',position};break;}}
   submitReport(candidate||{name:'Accident ahead on ambulance route',position:positionAlong(m,.65)},true);
  }}
 function startScenario(){setAssessment(null);setPhotoReset(n=>n+1);setLocked(false);setPlan(null);onPlan(null);setReports([]);setImpact(null);onEmergency();armedRef.current=true;setArmed(true);journey.current={progress:0,moving:true};setCommand({id:Date.now(),action:'restart'});}
 return <><div className="map-wrap"><TrafficMap network={network} route={route} layer={layer} focus={focus} reports={reports} oldPoints={impact?.affected?impact.oldPoints:null} command={command} onJourney={updateJourney} locked={locked}/><div className="map-label">{reports.length?'CITIZEN REPORT RESPONSE':'HISTORICAL ROAD REPLAY'}</div></div>
 <div className="incident-grid"><section className="citizen-report"><div className="section-kicker">CITIZEN REPORTING</div><h3>See an accident? Report it.</h3><p>Choose the affected road and describe the accident. Upload an accident photo. The image model assesses severity before routing is updated.</p><form onSubmit={e=>{e.preventDefault();submitReport(locations.find(p=>p.name===location)||locations[0]);}}><label>Accident location<select aria-label="Accident location" value={locations.some(p=>p.name===location)?location:locations[0]?.name||''} onChange={e=>setLocation(e.target.value)}>{locations.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>What happened?<textarea aria-label="Report details" maxLength={240} placeholder="e.g. Collision blocking the road" value={details} onChange={e=>setDetails(e.target.value)}/></label><AccidentPhoto key={photoReset} onChange={setAssessment}/><button className="primary" disabled={!locations.length||!assessment}>Submit accident report</button></form><button className="outline scenario-button" onClick={startScenario} disabled={!baseRoute||armed}>{armed?'Ambulance en route · report arriving…':'Run accident scenario'}</button><button className="text-button" onClick={()=>{setAssessment(null);setPhotoReset(n=>n+1);setLocked(false);setPlan(null);onPlan(null);setReports([]);setImpact(null);armedRef.current=false;setArmed(false);setCommand({id:Date.now(),action:'reset'});}}>Clear reports &amp; reset journey</button><small>Starts an ambulance; an accident is reported at 18% of its journey. Resets previous reports.</small></section>
 <section className="incident-impact" aria-label="Report impact" aria-live="polite"><div className="section-kicker">REPORT RESPONSE</div><h3>{impact?impact.outcome:'Listening for citizen reports'}</h3>{impact?<><ol><li><b>Report received</b><span>{impact.report.time} · {impact.report.road}{impact.report.demo?' · scenario report':''}</span>{impact.report.details&&<span>{impact.report.details}</span>}</li><li><b>{impact.affected?'Conflict detected ahead':'No conflict on remaining route'}</b><span>Unverified citizen report · severity-based traffic impact applied.</span></li><li><b>{impact.outcome}</b><span>{!impact.affected?'The reported location is outside the remaining path. Journey continues.':impact.after?'Remaining route recalculated from the vehicle’s current position, comparing congestion delay with available detours. Red dashes show the previous plan.':'Movement paused. No detour exists in the bundled road coverage; human review required.'}</span></li></ol><div className="severity-impact"><b>{severityProfiles[impact.report.severity]?.label} traffic severity</b><small>{impact.report.assessment.source}</small><p>{impact.report.assessment.summary}</p><div className="impact-times"><div><small>Estimated disruption</small><strong>{severityProfiles[impact.report.severity]?.closure}</strong></div><div><small>Local congestion estimate</small><strong>{severityProfiles[impact.report.severity]?.congestion}/100</strong></div></div><p>{severityProfiles[impact.report.severity]?.response}</p><small>Planning estimates · response requires human confirmation</small></div><div className="impact-times"><div><small>Before report</small><strong>{impact.before} min</strong></div><div><small>Updated remaining ETA</small><strong>{impact.after?`${impact.after} min`:impact.affected?'Unavailable':`${impact.before} min`}</strong></div></div><p>{impact.arrival&&`Estimated arrival: ${impact.arrival} (local time). `}{impact.after?`ETA change: ${impact.after-impact.before>=0?'+':''}${impact.after-impact.before} min. `:''}{reports.length} active report(s). </p></>:<p>Submit a report or run the accident scenario to see receipt, conflict detection, route changes and updated arrival estimates here.</p>}<small>Reports stay in this session.</small></section></div></>;
}
